// apps/work-client/src/pages/HomePage.tsx
import { BriefcaseBusiness } from "lucide-react";

import { workApiBaseUrl } from "../shared/api/http";

export function HomePage() {
  return (
    <main className="shell">
      <section className="hero" aria-labelledby="work-title">
        <div className="title-row">
          <BriefcaseBusiness aria-hidden="true" size={32} />
          <p className="eyebrow">Work subsystem</p>
        </div>
        <h1 id="work-title">Study2Work Work</h1>
        <p className="summary">
          Career profiles, CVs, jobs, applications, enterprise workflow, and Study evidence
          visibility will live here.
        </p>
        <dl className="facts">
          <div>
            <dt>API</dt>
            <dd>{workApiBaseUrl}</dd>
          </div>
          <div>
            <dt>Health</dt>
            <dd>/health/live</dd>
          </div>
        </dl>
      </section>
    </main>
  );
}

// apps/study-client/src/pages/HomePage.vue
<script setup lang="ts">
import { studyApiBaseUrl } from "../shared/api/http";
</script>

<template>
  <main class="shell">
    <section class="hero">
      <p class="eyebrow">Study subsystem</p>
      <h1>Study2Work Study</h1>
      <p class="summary">
        Learning paths, lessons, assessment, progress, and verified evidence will live here.
      </p>
      <dl class="facts">
        <div>
          <dt>API</dt>
          <dd>{{ studyApiBaseUrl }}</dd>
        </div>
        <div>
          <dt>Health</dt>
          <dd>/health/live</dd>
        </div>
      </dl>
    </section>
  </main>
</template>
